chore: Blockchain and database state persistence #closes #54

diff --git a/init b/init
--- a/init
+++ b/init
@@ -1,17 +1,115 @@
 #!/bin/bash
+
+
 source ./api-2.0/.env
+
+# TODO move to a global env setup
+PID_FILE=.carbon.pid
+
+SUCCESS_COLOR='\033[0;32m'
+WARNING_COLOR='\033[0;33m'
 INFO_COLOR='\033[0;34m'
+ERROR_COLOR='\033[0;31m'
 NC='\033[0m' # No Color
+
+unset reset_all
+unset skip_mysql
+unset fresh_inst
+fast_install="--prefer-offline --no-audit --progress=false"
+
+set -e
+
 
 #only try to start mysql if it is not running already, otherwise sudo would be invoked in vain
 start-mysql() {
-  if [[ $(ps aux | grep mysql | grep -v grep) ]]; then
-    echo "MySQL already running"
-  else
+  local mysql_up=$(ps aux | grep mysql | grep -v grep | wc -l);
+  if [ ${mysql_up} -ne 0 ]; then
+   echo -e "${SUCCESS_COLOR}MySQL already running${NC}"
+    return 0
+  fi
+  if [ -z "${skip_mysql}" ]; then
+    sudo -k # make sure to ask for password on next sudo
+    if ! sudo true; then
+        echo -e "${ERROR_COLOR} Wrong password, you need be sudo to start MySQL ${NC}"
+        exit 1
+    fi
     sudo systemctl start mysql
-    echo "Started MySQL"
+    echo "MySQL started ..."
+    local mysql_up=$(ps aux | grep mysql | grep -v grep | wc -l);
+    local tries=0
+    
+    while [ ${mysql_up} -eq 0 ] && [ ${tries} -le 10 ]; do
+      mysql_up=$(ps aux | grep mysql | grep -v grep | wc -l);
+      sleep 3
+      tries=$((tries+1))
+      echo echo -e "${INFO_COLOR}Waiting for MySQL ...${NC}"
+    done
+    if [ ${mysql_up} -eq 0 ]; then
+      echo -e "${ERROR_COLOR}Error starting MySQL, check process list${NC}"
+      exit 1
+    fi
+    echo -e "${SUCCESS_COLOR}Started MySQL${NC}"
+  else
+    echo -e "${WARNING_COLOR}Skipping MySQL startup${NC}"
+  fi
+  
+  if [ ${mysql_up} -eq 0 ]; then
+    echo -e "${ERROR_COLOR}MySQL is down.${NC}";
+    exit 1   
   fi
 }
+
+usage() {    
+  cat<<EOM
+    Usage:
+    $(basename $0) [-hrsi]
+    Start all containers and databases - skip channels creation/deploy, host setup, js bundles and change NPM start up
+    -r Reset all envirionments
+    -s Skip mysql start
+    -i Fresh install
+    -h Display a brief help message
+EOM
+  exit 1; 
+}
+
+while getopts ":hrsi" o; do
+    case "${o}" in     
+      s)
+        skip_mysql=1
+        ;;
+      i)
+        fresh_inst=1;
+        reset_all=1;
+        unset fast_install;
+        unset skip_mysql;
+        ;;
+      r)
+        reset_all=1;
+        unset skip_mysql;
+        unset fast_install;
+        ;;
+      *|has)
+        usage
+        ;;
+    esac
+done
+
+###
+# Start Process
+###
+
+if [[ "$EUID" = 0 ]]; then
+  echo -e "${ERROR_COLOR}Please do not run this script as root ${NC}" && exit 1 
+fi
+
+echo -e "${SUCCESS_COLOR}Running $(basename $0) process ${NC}"
+
+if [ -z "${skip_mysql}"  ] && ! [ -x "$(command -v sudo)" ]; then
+  echo 'Error: sudo  is not installed.' >&2
+  exit 1
+fi
+
+echo -e "${INFO_COLOR}Running processes [${PWD}]${NC}" 
 
 
 ###### Executable files (+x) ######
@@ -29,59 +127,74 @@ chmod +x api-2.0/public/scripts/src/genscripts.sh
 chmod +x api-2.0/config/generate-ccp.sh
 chmod +x api-2.0/get-bundles
 
-###### KILL ######
-#kill other dockers 
-echo -e "${INFO_COLOR}Docker compose setup:${NC}"
-docker-compose -f ./explorer/docker-compose.yaml down
-docker-compose -f ./artifacts/docker-compose.yaml down
-docker-compose -f ./artifacts/channel/create-certificate-with-ca/docker-compose.yaml down
-containers=$(docker ps -q) && [[ ! -z "$containers" ]] && docker kill $containers
-docker network prune -f && docker volume prune -f
 
-#remove couch-db instance, so identities get properly deleted
-# TODO - manage restart
-rm  ./artifacts/channel/create-certificate-with-ca/fabric-ca/carbon/fabric-ca-server.db
+###### KILL ######
+#kill other dockers and reset envirionments
+if [ -n "${reset_all}"  ]; then
+  echo -e "${WARNING_COLOR}Reseting all:${NC}"
+  ./kill -ry
+  echo $$ > ${PID_FILE}
+fi
+
+
+if [ ! -f "${PID_FILE}" ] && [ -n "${fresh_inst}"]; then
+  echo -e "${ERROR_COLOR}First install not found. Run ./init -i ${NC}" && exit 1 
+fi
 
 ###### RUN ######
 echo -e "${INFO_COLOR}Database setup:${NC}"
 #run mysql
 start-mysql
 
-# TODO - Manage restart
-./database/reset-db
 echo -e "${INFO_COLOR}Docker compose CA setup:${NC}"
 #run one docker for each CA (each org has 1, incluind the orderer)
 docker-compose -f ./artifacts/channel/create-certificate-with-ca/docker-compose.yaml up -d
-sleep 15
 
-#creates CAs and orgs certificates
-./artifacts/channel/create-certificate-with-ca/create-certificate-with-ca.sh
 
-# #create genisis block, config channel and generate anchors
-./artifacts/channel/create-artifacts.sh
+if [ -z "${fast_install}" ]; then
+  echo -e "${INFO_COLOR}Waiting for services to be up and running...${NC}"
+  sleep 15
+  echo -e "${INFO_COLOR}Creating CAs and orgs certificates:${NC}"
+  #creates CAs and orgs certificates
+  ./artifacts/channel/create-certificate-with-ca/create-certificate-with-ca.sh
 
-# exit
+  echo -e "${INFO_COLOR}Creating artifacts:${NC}"
+  # #create genisis block, config channel and generate anchors
+  ./artifacts/channel/create-artifacts.sh
+fi
 
 #run chouchdb, orgs peers and orderers dockers
-echo ${PWD}
 docker-compose -f artifacts/docker-compose.yaml up -d 
-sleep 15
 
 # #create channel and deploy chaincode on each org
-./createChannel.sh
-./deployChaincode.sh
+if [ -z "${fast_install}" ]; then
+  echo -e "${INFO_COLOR}Waiting for services to be up and running...${NC}"
+  sleep 15
+  echo -e "${INFO_COLOR}Creating channels:${NC}"
+  ./createChannel.sh
+  echo -e "${INFO_COLOR}Deploying channels:${NC}"
+  ./deployChaincode.sh
+fi
 
 # #create connection profiles if they don't exist already
-[ -f ./api-2.0/config/connection-carbon.json ] || ./api-2.0/config/generate-ccp.sh
+
+if [ ! -f ./api-2.0/config/connection-carbon.json ]; then
+  echo -e "${INFO_COLOR}Generating CCP:${NC}"
+  ./api-2.0/config/generate-ccp.sh
+fi
 
 # #create public scripts
-./api-2.0/public/scripts/src/genscripts.sh
-
+if [ -z "${fast_install}" ]; then
+  echo -e "${INFO_COLOR}Generating Scripts:${NC}"
+  ./api-2.0/public/scripts/src/genscripts.sh
+  echo -e "${INFO_COLOR}Generating Bundles:${NC}"
+  #generate bundle
+  ./api-2.0/get-bundles
+fi
 (
   cd api-2.0/
-  #generate bundle
-  ./get-bundles
   #start service
-  npm install
+  echo -e "${INFO_COLOR}npm install ${fast_install}${NC}"
+  npm install ${fast_install}
   nodemon
 )
diff --git a/kill b/kill
--- a/kill
+++ b/kill
@@ -1,22 +1,154 @@
 #!/bin/bash
 
-###### KILL ######
-kill-hlf () {
-	docker-compose down 
-	containers=$(docker ps -q) && docker kill $containers
-	docker network prune -f && docker volume prune -f
+# TODO move to a global env setup
+PID_FILE=.carbon.pid
+
+###
+# Removable package Chaincoide files (Chaincode name)
+###
+CC_NAME="erc1155"
+
+###
+#Color config
+##
+SUCCESS_COLOR='\033[0;32m'
+WARNING_COLOR='\033[0;33m'
+INFO_COLOR='\033[0;34m'
+ERROR_COLOR='\033[0;31m'
+NC='\033[0m' # No Color
+
+unset reset_soft
+unset yes_all
+unset skip_mysql
+unset reset_hard
+
+if [[ "$EUID" = 0 ]]; then
+    echo -e "${ERROR_COLOR}Please do not run this script as root ${NC}" && exit 1 
+fi
+
+
+usage() {
+    cat<<EOM
+    Usage:
+    $(basename $0) [-hrys]
+    Stop all containers and databases
+    -r Reset envirionment (dockers, couchDB and MySQL)
+    -y Non-interactively (sudo may be required)
+    -s Skip mysql stop
+    -a Remove all docker related (docker system prune -a --volumes)
+    -h Display a brief help message
+EOM
+exit 0; 
+}
+while getopts ":hrya" o; do
+    case "${o}" in
+      r)
+        reset_soft=1
+        ;;
+      s)
+        skip_mysql=1
+        ;;
+      a)
+        reset_soft=1
+        reset_hard=1
+        ;;
+      y)
+        yes_all=1
+        ;;
+      *|h)
+        echo "usage"
+        usage
+        ;;
+    esac
+done
+
+
+reset_soft_applications(){
+  echo -e "${WARNING_COLOR}RESETING ENV!${NC}"
+  if [ -z "${yes_all}" ]; then
+    echo -e "${WARNING_COLOR}Are you sure?(yY) ${NC}"
+    read -n 1 -r
+    echo    # (optional) move to a new line
+    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
+        exit 1 
+    fi
+  fi
+
+  #kill other dockers 
+  echo -e "${WARNING_COLOR}Reseting Docker Containers${NC}"
+  docker-compose -f ./explorer/docker-compose.yaml down
+  docker-compose -f ./artifacts/docker-compose.yaml down
+  docker-compose -f ./artifacts/channel/create-certificate-with-ca/docker-compose.yaml down
+
+  containers=$(docker ps -q) && [[ ! -z "$containers" ]] && docker kill $containers
+  if [ "${reset_hard}" == "1" ]; then
+    docker system prune -a --volumes
+  else
+    docker network prune -f && docker volume prune -f
+  fi
+  #Reset database
+  echo -e "${WARNING_COLOR}Reseting MySQL${NC}"
+  ./database/reset-db
+  echo -e "${WARNING_COLOR}Reseting CouchDB${NC}"
+  db_file=./artifacts/channel/create-certificate-with-ca/fabric-ca/carbon/fabric-ca-server.db
+  [ -f ${db_file} ] && rm -f ${db_file}
+
+  #Remove old Crypto
+  rm -rf ./api-1.4/crypto/*
+  rm -rf ./api-1.4/fabric-client-kv-carbon/*
+  rm -rf ./api-2.0/carbon-wallet/*
+  rm -rf ./api-2.0/users-wallet/*
+
+  #Clear channel artifacts
+  rm -rf ./channel-artifacts/*
+
+  # Delete existing artifacts
+  rm -rf ./artifacts/channels/genesis.block ./artifacts/channels/mychannel.tx
+  rm -rf ./channel-artifacts/*
+  #Remove package chaincode
+  rm -rf ./${CC_NAME}.tar.gz
+  
+  #Remove old crypto config
+  rm -rf ./artifacts/channel/crypto-config/*
+  
+  #clear git ignored files
+  git clean -dfX
+  rm -rf ${PID_FILE}
 }
 
-#kill other dockers 
-cd ./explorer
-kill-hlf
-cd ../artifacts
-kill-hlf
-cd channel/create-certificate-with-ca
-kill-hlf
+stop_applications(){
+  docker-compose -f ./explorer/docker-compose.yaml stop
+  docker-compose -f ./artifacts/docker-compose.yaml stop
+  docker-compose -f ./artifacts/channel/create-certificate-with-ca/docker-compose.yaml stop
+}
 
-#stop mysql
-sudo systemctl stop mysql
+###
+# Process started
+###
+echo -e "${SUCCESS_COLOR}Running $(basename $0) process ${NC}"
 
-#clear git ignored
-git clean -dfX
+if [ -z "${skip_mysql}" ] && ! [ -x "$(command -v sudo)" ]; then
+  echo 'Error: sudo  is not installed.' >&2
+  exit 1
+fi
+
+if [ "${reset_soft}" == "1" ]; then
+  reset_soft_applications
+else
+  stop_applications
+fi
+
+
+if [ -z "${skip_mysql}" ]; then
+  #stop mysql
+  sudo systemctl stop mysql
+fi
+
+#remove sudo cache
+if [ "${reset_soft}" == "1" ]; then
+	sudo -k
+fi
+
+###
+# Process finished
+###
